version: '3.7'

services:
  node:
    image: node
    restart: always
    volumes:
      - ./:/home/node
    user: root
    working_dir: /home/node
    network_mode: host
#    environment:
#      - http_proxy=http://127.0.0.1:2000
#      - https_proxy=http://127.0.0.1:2000

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./build:/var/www/html
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 8999:80
